(ns gravity.cli.commands.platform
  "Bootstrap backend, runtime, and platform command ownership.")

(def commands
  {"backend-interface" 'backend-interface-file-artifact
   "native-lowering" 'native-lowering-file-artifact
   "hosted-lowering" 'hosted-lowering-file-artifact
   "specialized-lowering" 'specialized-lowering-file-artifact
   "artifact-emission" 'artifact-emission-file-artifact
   "backend-test-matrix" 'backend-test-matrix-file-artifact
   "backend-b1-document" 'b1-document-file-artifact
   "backend-b2-c-document" 'b2-document-file-artifact
   "backend-b3-llvm-document" 'b3-document-file-artifact
   "backend-b4-wasm-document" 'b4-document-file-artifact
   "backend-b5-jvm-document" 'b5-document-file-artifact
   "backend-b6-js-ts-document" 'b6-document-file-artifact
   "backend-b7-mlir-document" 'b7-document-file-artifact
   "backend-b8-gpu-document" 'b8-document-file-artifact
   "backend-b9-hdl-document" 'b9-document-file-artifact
   "backend-b10-workflow-document" 'b10-document-file-artifact
   "backend-b11-query-document" 'b11-document-file-artifact
   "backend-b12-mobile-document" 'b12-document-file-artifact
   "backend-b13-artifact-document" 'b13-document-file-artifact
   "backend-b14-conformance-document" 'b14-document-file-artifact
   "runtime-selection" 'runtime-selection-file-artifact
   "runtime-minimal-native" 'minimal-native-memory-file-artifact
   "runtime-managed" 'managed-runtime-file-artifact
   "runtime-concurrency" 'concurrency-distributed-file-artifact
   "runtime-ai-ffi" 'ai-repl-ffi-capability-file-artifact
   "runtime-observability" 'runtime-observability-file-artifact
   "runtime-r1-document" 'r1-document-file-artifact
   "runtime-r2-document" 'r2-document-file-artifact
   "runtime-r3-document" 'r3-document-file-artifact
   "runtime-r4-document" 'r4-document-file-artifact
   "runtime-r5-document" 'r5-document-file-artifact
   "runtime-r6-document" 'r6-document-file-artifact
   "runtime-r7-document" 'r7-document-file-artifact
   "runtime-r8-document" 'r8-document-file-artifact
   "runtime-r9-document" 'r9-document-file-artifact
   "runtime-r10-document" 'r10-document-file-artifact
   "runtime-r11-document" 'r11-document-file-artifact
   "runtime-r12-document" 'r12-document-file-artifact
   "domain-coverage" 'domain-coverage-file-artifact
   "schema-interop" 'schema-interop-file-artifact
   "ai-agentic" 'ai-agentic-file-artifact
   "package-artifacts" 'package-artifacts-file-artifact
   "tooling-experience" 'tooling-experience-file-artifact
   "conformance-system" 'conformance-system-file-artifact
   "standard-library" 'standard-library-file-artifact
   "governance-evolution" 'governance-evolution-file-artifact
   "hosted-core-app" 'hosted-core-app-proof-file-artifact
   "hosted-core-compiled-app" 'hosted-core-compiled-app-proof-file-artifact
   "hosted-core-compiled-safety" 'hosted-core-compiled-safety-proof-file-artifact
   "hosted-core-compiled-profile" 'hosted-core-compiled-profile-proof-file-artifact
   "hosted-core-compiled-performance" 'hosted-core-compiled-performance-proof-file-artifact
   "hosted-core-compiled-math" 'hosted-core-compiled-math-proof-file-artifact
   "hosted-core-compiled-compiler" 'hosted-core-compiled-compiler-proof-file-artifact
   "hosted-core-compiled-backend" 'hosted-core-compiled-backend-proof-file-artifact
   "hosted-core-compiled-runtime" 'hosted-core-compiled-runtime-proof-file-artifact
   "hosted-core-compiled-domain" 'hosted-core-compiled-domain-proof-file-artifact
   "hosted-core-compiled-schema" 'hosted-core-compiled-schema-proof-file-artifact
   "hosted-core-compiled-ai" 'hosted-core-compiled-ai-proof-file-artifact
   "hosted-core-compiled-package" 'hosted-core-compiled-package-proof-file-artifact
   "hosted-core-compiled-tooling" 'hosted-core-compiled-tooling-proof-file-artifact
   "hosted-core-compiled-conformance" 'hosted-core-compiled-conformance-proof-file-artifact})
