(defn-
 semantic-llvm-linux-toolchain-execution!
 [candidate
  source-path
  lowering
  workspace
  ir-path
  object-path
  executable-path
  image
  target
  primary-failure]
 (let
  [version-step
   (p15-s23-b3-llvm-linux-run-step!
    candidate
    workspace
    source-path
    :docker-version
    ["docker" "version" "--format" "{{json .Server}}"])
   info-step
   (p15-s23-b3-llvm-linux-run-step!
    candidate
    workspace
    source-path
    :docker-info
    ["docker" "info" "--format" "{{json .}}"])
   image-step
   (p15-s23-b3-llvm-linux-run-step!
    candidate
    workspace
    source-path
    :image-inspect
    ["docker" "image" "inspect" image])
   clang-step
   (p15-s23-b3-llvm-linux-run-step!
    candidate
    workspace
    source-path
    :clang-version
    (p15-s23-b3-llvm-linux-docker-command
     workspace
     ["clang" "--version"]))
   llvm-step
   (p15-s23-b3-llvm-linux-run-step!
    candidate
    workspace
    source-path
    :llvm-version
    (p15-s23-b3-llvm-linux-docker-command
     workspace
     ["llvm-readobj" "--version"]))
   triple-step
   (p15-s23-b3-llvm-linux-run-step!
    candidate
    workspace
    source-path
    :clang-target-triple
    (p15-s23-b3-llvm-linux-docker-command
     workspace
     ["clang" "-target" target "-print-target-triple"]))
   hashes-step
   (p15-s23-b3-llvm-linux-run-step!
    candidate
    workspace
    source-path
    :llvm-tool-hashes
    (p15-s23-b3-llvm-linux-docker-command
     workspace
     ["sh"
      "-lc"
      "set -eu; for t in clang llc opt llvm-as llvm-dis llvm-readobj llvm-objdump ld.lld; do p=$(command -v \"$t\"); test -n \"$p\"; case \"$p\" in /*) ;; *) exit 64 ;; esac; h=$(sha256sum \"$p\" | cut -d' ' -f1); printf '%s %s sha256:%s\\n' \"$t\" \"$p\" \"$h\"; done"]))
   emulation-step
   (p15-s23-b3-llvm-linux-run-step!
    candidate
    workspace
    source-path
    :emulation-environment
    (p15-s23-b3-llvm-linux-docker-command
     workspace
     ["sh"
      "-lc"
      "arch=$(uname -m); kernel=$(uname -r); printf 'uname -m %s\\nkernel %s\\n' \"$arch\" \"$kernel\"; if [ -r /proc/sys/fs/binfmt_misc/status ]; then printf 'binfmt-status '; cat /proc/sys/fs/binfmt_misc/status; else printf '%s\\n' 'binfmt-status unavailable'; fi; if command -v qemu-x86_64-static >/dev/null 2>&1; then p=$(command -v qemu-x86_64-static); printf 'qemu-x86_64-static %s\\n' \"$p\"; else printf '%s\\n' 'qemu-x86_64-static unavailable'; fi"]))
   object-step
   (p15-s23-b3-llvm-linux-run-step!
    candidate
    workspace
    source-path
    :llvm-to-object
    (p15-s23-b3-llvm-linux-docker-command
     workspace
     ["clang"
      "-target"
      target
      "-x"
      "ir"
      "-Werror=override-module"
      "-O0"
      "-fPIC"
      "-mcmodel=small"
      "-mcpu=generic"
      "-c"
      "/work/program.ll"
      "-o"
      "/work/program.o"]))
   object-snapshot
   (p15-s23-b3-llvm-file-snapshot!
    candidate
    workspace
    object-path
    source-path
    :linux-elf-object-snapshot
    p15-s23-b3-llvm-max-emitted-file-bytes)
   link-step
   (p15-s23-b3-llvm-linux-run-step!
    candidate
    workspace
    source-path
    :link
    (p15-s23-b3-llvm-linux-docker-command
     workspace
     ["clang"
      "-target"
      target
      "-fuse-ld=lld"
      "-no-pie"
      "/work/program.o"
      "-o"
      "/work/program"]))
   executable-snapshot
   (p15-s23-b3-llvm-file-snapshot!
    candidate
    workspace
    executable-path
    source-path
    :linux-elf-executable-snapshot
    p15-s23-b3-llvm-max-emitted-file-bytes)
   object-header-step
   (p15-s23-b3-llvm-linux-run-step!
    candidate
    workspace
    source-path
    :elf-object-header
    (p15-s23-b3-llvm-linux-docker-command
     workspace
     ["llvm-readobj" "--file-headers" "/work/program.o"]))
   executable-header-step
   (p15-s23-b3-llvm-linux-run-step!
    candidate
    workspace
    source-path
    :elf-executable-header
    (p15-s23-b3-llvm-linux-docker-command
     workspace
     ["llvm-readobj" "--file-headers" "/work/program"]))
   sections-step
   (p15-s23-b3-llvm-linux-run-step!
    candidate
    workspace
    source-path
    :elf-sections
    (p15-s23-b3-llvm-linux-docker-command
     workspace
     ["llvm-readobj" "--sections" "/work/program.o" "/work/program"]))
   providers-step
   (p15-s23-b3-llvm-linux-run-step!
    candidate
    workspace
    source-path
    :runtime-providers
    (p15-s23-b3-llvm-linux-docker-command
     workspace
     ["llvm-readobj" "--needed-libs" "/work/program"]))
   run-step
   (p15-s23-b3-llvm-linux-run-step!
    candidate
    workspace
    source-path
    :run
    (p15-s23-b3-llvm-linux-docker-command
     workspace
     ["/work/program"]))]
  (hash-map
   :version-step
   version-step
   :info-step
   info-step
   :image-step
   image-step
   :clang-step
   clang-step
   :llvm-step
   llvm-step
   :triple-step
   triple-step
   :hashes-step
   hashes-step
   :emulation-step
   emulation-step
   :object-step
   object-step
   :object-snapshot
   object-snapshot
   :link-step
   link-step
   :executable-snapshot
   executable-snapshot
   :object-header-step
   object-header-step
   :executable-header-step
   executable-header-step
   :sections-step
   sections-step
   :providers-step
   providers-step
   :run-step
   run-step)))
