(defn-
 semantic-llvm-legacy-toolchain-phase-01!
 [candidate
  source-path
  lowering
  publication-intent?
  workspace
  ir-path
  object-path
  executable-path
  target
  primary-failure]
 (let
  [_
   (java.nio.file.Files/setPosixFilePermissions
    workspace
    p15-s23-b3-llvm-private-directory-permissions)
   toolchain
   (p15-s23-b3-llvm-toolchain-preflight!
    candidate
    workspace
    source-path)
   sdk-path
   (:sdk-actual-path toolchain)
   clang-path
   (:clang-actual-path toolchain)
   ld-path
   (:ld-actual-path toolchain)
   otool-path
   (:otool-actual-path toolchain)
   file-path
   (:file-actual-path toolchain)
   compile-command
   [clang-path
    "-target"
    target
    "-isysroot"
    sdk-path
    "-x"
    "ir"
    "-Werror=override-module"
    "-O0"
    "-fPIC"
    "-mcmodel=small"
    "-mcpu=generic"
    "-Xclang"
    "-target-feature"
    "-Xclang"
    "+v8a"
    "-Xclang"
    "-target-feature"
    "-Xclang"
    "+fp-armv8"
    "-Xclang"
    "-target-feature"
    "-Xclang"
    "+neon"
    "-c"
    "program.ll"
    "-o"
    "program.o"]
   link-command
   [clang-path
    "-target"
    target
    "-isysroot"
    sdk-path
    "-Wl,-reproducible"
    (str "-fuse-ld=" ld-path)
    "program.o"
    "-o"
    "program"]
   _
   (java.nio.file.Files/write
    ir-path
    (.getBytes
     (:llvm-ir lowering)
     java.nio.charset.StandardCharsets/UTF_8)
    (into-array
     java.nio.file.OpenOption
     [java.nio.file.StandardOpenOption/CREATE_NEW
      java.nio.file.StandardOpenOption/WRITE]))
   _
   (java.nio.file.Files/setPosixFilePermissions
    ir-path
    p15-s23-b3-llvm-nonexecutable-permissions)
   ir-canonical
   (p15-s23-b3-llvm-file-snapshot!
    candidate
    workspace
    ir-path
    source-path
    :canonical-pre-tool-llvm-ir
    p15-s23-b3-llvm-max-emitted-file-bytes)
   compile-step
   (p15-s23-b3-llvm-run-step!
    candidate
    workspace
    source-path
    :llvm-to-object
    compile-command)
   _
   (java.nio.file.Files/setPosixFilePermissions
    object-path
    p15-s23-b3-llvm-nonexecutable-permissions)
   object-canonical
   (p15-s23-b3-llvm-file-snapshot!
    candidate
    workspace
    object-path
    source-path
    :canonical-pre-verification-object
    p15-s23-b3-llvm-max-emitted-file-bytes)
   link-step
   (p15-s23-b3-llvm-run-step!
    candidate
    workspace
    source-path
    :link
    link-command)
   _
   (java.nio.file.Files/setPosixFilePermissions
    executable-path
    p15-s23-b3-llvm-executable-permissions)
   executable-canonical
   (p15-s23-b3-llvm-file-snapshot!
    candidate
    workspace
    executable-path
    source-path
    :canonical-pre-verification-executable
    p15-s23-b3-llvm-max-emitted-file-bytes)
   file-step
   (p15-s23-b3-llvm-run-step!
    candidate
    workspace
    source-path
    :file-format
    [file-path "program.o" "program"])
   header-step
   (p15-s23-b3-llvm-run-step!
    candidate
    workspace
    source-path
    :mach-o-header
    [otool-path "-hv" "program.o" "program"])
   load-step
   (p15-s23-b3-llvm-run-step!
    candidate
    workspace
    source-path
    :mach-o-load-commands
    [otool-path "-l" "program.o" "program"])
   provider-step
   (p15-s23-b3-llvm-run-step!
    candidate
    workspace
    source-path
    :runtime-providers
    [otool-path "-L" "program"])
   file-output
   (get-in file-step [:result :stdout :text])
   header-output
   (get-in header-step [:result :stdout :text])]
  (hash-map
   :toolchain
   toolchain
   :sdk-path
   sdk-path
   :clang-path
   clang-path
   :ld-path
   ld-path
   :otool-path
   otool-path
   :file-path
   file-path
   :compile-command
   compile-command
   :link-command
   link-command
   :ir-canonical
   ir-canonical
   :compile-step
   compile-step
   :object-canonical
   object-canonical
   :link-step
   link-step
   :executable-canonical
   executable-canonical
   :file-step
   file-step
   :header-step
   header-step
   :load-step
   load-step
   :provider-step
   provider-step
   :file-output
   file-output
   :header-output
   header-output)))
