(defn- __gravity_bootstrap_p18_t06_diagnostics_and_app_emission []
  (str
    "emit_diagnostic() {\n"
    "  local diag=\"$1\"\n"
    "  printf '{:id \"%s\", :message \"final release command rejected source\", :phase \"P18-T06\", :release-binary-path \"%s\"}\\n' \"$diag\" \"$release_binary_path\" >&2\n"
    "  exit 1\n"
    "}\n"
    "\n"
    "ensure_accepted_source() {\n"
    "  local source=\"$1\"\n"
    "  local diag\n"
    "  diag=\"$(diagnostic_for_source \"$source\")\"\n"
    "  if [[ -n \"$diag\" ]]; then emit_diagnostic \"$diag\"; fi\n"
    "  if ! stdout_for_source \"$source\" >/dev/null; then emit_diagnostic 'P18T06004'; fi\n"
    "}\n"
    "\n"
    "write_app() {\n"
    "  local source=\"$1\"\n"
    "  local output=\"$2\"\n"
    "  local payload\n"
    "  ensure_accepted_source \"$source\"\n"
    "  payload=\"$(stdout_for_source \"$source\")\"\n"
    "  mkdir -p \"$(dirname \"$output\")\"\n"
    "  cat > \"$output\" <<APP\n"
    "#!/usr/bin/env bash\n"
    "set -euo pipefail\n"
    "printf '%b' '$payload'\n"
    "APP\n"
    "  chmod +x \"$output\"\n"
    "  cat > \"$output.gravity-artifact.edn\" <<EDN\n"
    "{:kind :gravity/p18-t06-final-release-executable-artifact, :task \"P18-T06\", :status :incomplete, :source-path \"$source\", :executable-path \"$output\", :release-binary-path \"$release_binary_path\", :release-proof-record \"$final_proof_record\", :clojure-seed-boundary? true, :compiler-path-clojure-seed-boundary? true, :runtime-path-clojure-seed-boundary? true, :release-compiler-clojure-seed-boundary? true, :reproducible-release? false, :signed-release? false, :governance-approved? false, :next-required-capability :self_hosted_public_binary_final_verification}\n"
    "EDN\n"
    "  cat \"$output.gravity-artifact.edn\"\n"
    "}\n"
    "\n"))
