(defn- __gravity_bootstrap_p18_t06_command_dispatch []
  (str
    "cmd=\"${1:-help}\"\n"
    "case \"$cmd\" in\n"
    "  --version|version)\n"
    "    printf '%s\\n' '{:command \"gravity\", :phase \"P18-T06\", :seedless-release? false, :final-release? false, :reproducible-release? false, :signed-release? false, :governance-approved? false, :clojure-seed-boundary? true, :release-proof \"docs/artifacts/phase-18/release/p18-t06-final-release-proof.edn\", :next-required-capability :self_hosted_public_binary_final_verification}'\n"
    "    ;;\n"
    "  --assert-seedless-release|assert-seedless-release)\n"
    "    printf '%s\\n' '{:id \"P18T06003\", :message \"final release candidate is blocked by the active Clojure seed boundary\", :phase \"P18-T06\", :seedless-release? false, :final-release? false, :clojure-seed-boundary? true}' >&2\n"
    "    exit 1\n"
    "    ;;\n"
    "  p18-t06-final-release|final-release-proof|release-proof)\n"
    "    cat \"$root_dir/$final_proof_record\"\n"
    "    ;;\n"
    "  p18-t06-provenance|provenance)\n"
    "    cat \"$root_dir/$provenance_record\"\n"
    "    ;;\n"
    "  p18-t06-sbom|sbom)\n"
    "    cat \"$root_dir/$sbom_record\"\n"
    "    ;;\n"
    "  p18-t06-signing|signing)\n"
    "    cat \"$root_dir/$signing_record\"\n"
    "    ;;\n"
    "  p18-t06-governance|governance)\n"
    "    cat \"$root_dir/$governance_record\"\n"
    "    ;;\n"
    "  p18-t05-seedless-release-boundary|seedless-boundary-proof)\n"
    "    cat \"$root_dir/$release_boundary_record\"\n"
    "    ;;\n"
    "  test)\n"
    "    if [[ -n \"${2:-}\" ]]; then\n"
    "      printf '%s\\n' '{:id \"P18T04006\", :message \"bootstrap-hosted public test command cannot be claimed as full language conformance\", :phase \"P18-T04\", :bootstrap-hosted? true, :full-language-conformance? false}' >&2\n"
    "      exit 1\n"
    "    fi\n"
    "    (cd \"$root_dir\" && clojure -M:gravity test)\n"
    "    ;;\n"
    "  self-host)\n"
    "    if [[ \"${2:-}\" != 'verify' || -n \"${3:-}\" ]]; then\n"
    "      printf '%s\\n' '{:id \"P18T04008\", :message \"public self-host verification command usage is invalid\", :phase \"P18-T04\", :expected-command [\"gravity\" \"self-host\" \"verify\"]}' >&2\n"
    "      exit 2\n"
    "    fi\n"
    "    (cd \"$root_dir\" && clojure -M:gravity p18-t04-write-public-self-host-verify-command-artifacts >/dev/null)\n"
    "    printf '%s\\n' '{:id \"P18T04007\", :message \"public self-host verification is blocked by the active Clojure seed boundary\", :phase \"P18-T04\", :bootstrap-hosted? true, :full-language-compiler-self-hosted? false, :clojure-seed-boundary? true, :proof-artifact \"docs/artifacts/phase-18/command/p18-t04-public-self-host-verify-command-proof.edn\"}' >&2\n"
    "    exit 1\n"
    "    ;;\n"
    "  inspect|artifact)\n"
    "    cat \"${2:?artifact path required}\"\n"
    "    ;;\n"
    "  check)\n"
    "    source=\"${2:?source path required}\"\n"
    "    diag=\"$(diagnostic_for_source \"$source\")\"\n"
    "    if [[ -n \"$diag\" ]]; then emit_diagnostic \"$diag\"; fi\n"
    "    if stdout_for_source \"$source\" >/dev/null; then\n"
    "      printf 'gravity blocked release candidate check passed: %s\\n' \"$(module_for_source \"$source\")\"\n"
    "    else\n"
    "      bootstrap_check_source \"$source\"\n"
    "    fi\n"
    "    ;;\n"
    "  run)\n"
    "    source=\"${2:?source path required}\"\n"
    "    ensure_accepted_source \"$source\"\n"
    "    printf '%b' \"$(stdout_for_source \"$source\")\"\n"
    "    ;;\n"
    "  compile)\n"
    "    source=\"${2:?source path required}\"\n"
    "    flag=\"${3:-}\"\n"
    "    output=\"${4:-}\"\n"
    "    if [[ \"$flag\" != '-o' && \"$flag\" != '--output' ]]; then emit_diagnostic 'P18T04002'; fi\n"
    "    if [[ -z \"$output\" || \"$output\" = /* || \"$output\" = *'..'* ]]; then emit_diagnostic 'P18T04002'; fi\n"
    "    write_app \"$source\" \"$output\"\n"
    "    ;;\n"
    "  help|--help|-h)\n"
    "    printf '%s\\n' 'gravity P18-T06 blocked final-release candidate'\n"
    "    printf '%s\\n' 'commands: check <QST/Gravity source file>, run <QST/Gravity source file>, compile <QST/Gravity source file> -o <exe>, test, self-host verify, inspect <artifact>, release-proof, sbom, signing, provenance, governance'\n"
    "    ;;\n"
    "  *)\n"
    "    printf 'unknown command: %s\\n' \"$cmd\" >&2\n"
    "    exit 2\n"
    "    ;;\n"
    "esac\n"))
