; Semantic decomposition of HEAD reader line 12567.
; Loaded into gravity.bootstrap; intentionally no ns form.

(def
 semantic-early-typed-pass-emits-01
 [:type-facts
  :effect-facts
  :memory-facts
  :concurrency-facts
  :capability-requirements
  :provider-selection-records
  :runtime-check-records
  :type-category-coverage
  :mir-type-preservation-records
  :effect-registry-snapshot
  :build-effect-log
  :replay-effect-log
  :handled-effect-table
  :handler-capability-and-profile-report
  :continuation-and-replay-safety-report
  :mir-effect-annotations
  :match-decision-tree-artifact
  :exhaustiveness-report
  :branch-type-narrowing-table
  :branch-effect-summary
  :unreachable-branch-diagnostics
  :match-schema-validation-links
  :pattern-ownership-facts
  :pattern-conformance-fixture
  :protocol-table
  :implementation-table
  :method-signature-records
  :dispatch-mode-records
  :multimethod-dispatch-tables
  :interface-lowering-artifacts
  :host-interop-dispatch-records
  :dispatch-conformance-fixture
  :error-type-declarations
  :thrown-error-effect-records
  :panic-lowering-records
  :safety-check-failure-records
  :ffi-error-mapping-artifacts
  :workflow-failure-records
  :ai-tool-error-records
  :host-error-normalization-records
  :error-conformance-fixture
  :memory-regime-annotations
  :ownership-borrow-facts
  :lifetime-region-facts
  :initialization-facts
  :allocation-effect-records
  :linear-resource-table
  :unsafe-raw-memory-audit-records
  :mmio-capability-records
  :allocator-runtime-manifests
  :memory-conformance-fixture
  :concurrency-effect-records
  :task-scope-graphs
  :concurrency-ownership-transfer-records
  :synchronization-facts])
