; Semantic decomposition of HEAD reader line 12567.
; Loaded into gravity.bootstrap; intentionally no ns form.

(def
 semantic-early-typed-pass-emits-05
 [:safe11-sink-authorization-records
  :safe11-parameterization-records
  :safe11-deserialization-records
  :safe11-secret-redaction-records
  :safe11-prompt-tool-policy-records
  :safe11-generated-taint-propagation
  :safe11-unsafe-clear-audits
  :safe11-conformance-fixture
  :safe10-capability-requirement-records
  :safe10-grant-intersection-records
  :safe10-provider-selection-records
  :safe10-scope-check-records
  :safe10-attenuation-records
  :safe10-revocation-records
  :safe10-secret-redaction-records
  :safe10-runtime-check-records
  :safe10-usage-summaries
  :safe10-conformance-fixture
  :safe14-package-safety-manifests
  :safe14-lockfile-records
  :safe14-build-effect-summaries
  :safe14-runtime-capability-summaries
  :safe14-unsafe-summaries
  :safe14-native-dependency-records
  :safe14-generated-artifact-provenance
  :safe14-signature-attestation-records
  :safe14-authority-diff-records
  :safe14-conformance-fixture
  :safe12-macro-safety-declarations
  :safe12-generated-origin-chains
  :safe12-macro-build-effect-records
  :safe12-generated-unsafe-island-records
  :safe12-hygiene-capture-records
  :safe12-taint-capability-propagation
  :safe12-facet-output-records
  :safe12-alternative-engine-equivalence
  :safe12-conformance-fixture
  :safe13-model-call-traces
  :safe13-tool-call-traces
  :safe13-prompt-provenance-records
  :safe13-tool-schema-validation-records
  :safe13-human-review-records
  :safe13-replay-records
  :safe13-model-output-taint-records
  :safe13-generated-code-safety-records
  :safe13-memory-retention-policies
  :safe13-conformance-fixture
  :safe15-proof-records
  :safe15-certificates
  :safe15-check-erasure-records
  :safe15-trust-records
  :safe15-invalidation-records
  :safe15-imported-certificate-verifications
  :safe15-proof-provider-records
  :safe15-unsafe-wrapper-audit-views])
