; Semantic decomposition of HEAD reader line 12567.
; Loaded into gravity.bootstrap; intentionally no ns form.

(def
 semantic-early-typed-pass-emits-03
 [:alternative-type-proof-artifacts
  :alternative-type-runtime-check-records
  :alternative-type-diagnostic-mapping-records
  :alternative-type-compatibility-reports
  :alternative-type-profile-soundness-evidence
  :alternative-type-effect-capability-records
  :alternative-type-ownership-facts
  :alternative-type-gradual-boundaries
  :alternative-type-domain-facts
  :alternative-type-optimization-proofs
  :alternative-type-conformance-fixture
  :alternative-memory-provider-declarations
  :alternative-memory-allocation-strategies
  :alternative-memory-lifetime-facts
  :alternative-memory-unsafe-boundary-audits
  :alternative-memory-layout-metadata
  :alternative-memory-runtime-checks
  :alternative-memory-release-evidence
  :alternative-memory-device-maps
  :alternative-memory-ffi-allocator-records
  :alternative-memory-conformance-reports
  :alternative-memory-safety-classifications
  :alternative-memory-conformance-fixture
  :interop-foreign-binding-declarations
  :interop-boundary-metadata
  :interop-generated-binding-provenance
  :interop-safe-wrapper-audits
  :interop-type-mapping-records
  :interop-ownership-lifetime-maps
  :interop-error-translation-maps
  :interop-capability-effect-records
  :interop-migration-shim-records
  :interop-parity-test-reports
  :interop-compatibility-records
  :interop-schema-drift-records
  :interop-profile-rejection-records
  :interop-conformance-fixture
  :safe1-safety-classification-records
  :safe1-runtime-check-records
  :safe1-unsafe-island-audit-records
  :safe1-generated-code-safety-provenance
  :safe1-optimization-check-erasure-justifications
  :safe1-dependency-safety-mode-records
  :safe1-conformance-fixture
  :safe-memory-operation-records
  :safe-memory-runtime-check-records
  :safe-memory-allocation-release-maps
  :safe-memory-escape-analysis-records
  :safe-memory-proof-records
  :safe-memory-backend-preservation-records
  :safe-memory-unsafe-audit-records
  :safe-memory-ownership-graphs
  :safe-memory-borrow-graphs
  :safe-memory-lifetime-interval-maps
  :safe-memory-transfer-records])
