; Semantic decomposition of HEAD reader line 12567.
; Loaded into gravity.bootstrap; intentionally no ns form.

(def
 semantic-early-typed-pass-emits-02
 [:atomic-ordering-records
  :actor-channel-schemas
  :workflow-replay-records
  :scheduler-runtime-manifests
  :race-analysis-reports
  :concurrency-conformance-fixture
  :compile-time-evaluation-trace
  :constant-value-table
  :generated-form-provenance-records
  :hermetic-replay-records
  :cache-key-records
  :compile-time-capability-proof-records
  :compile-time-conformance-fixture
  :standard-library-namespace-contracts
  :standard-library-api-contracts
  :standard-library-profile-availability-reports
  :standard-library-documentation-examples
  :standard-library-unsafe-wrapper-audits
  :standard-library-compatibility-records
  :standard-library-numeric-mode-records
  :standard-library-resource-records
  :standard-library-conformance-fixture
  :facet-manifests
  :facet-activation-records
  :facet-generated-gravity-records
  :facet-domain-ir-records
  :facet-composition-records
  :facet-privacy-boundary-records
  :facet-compatibility-records
  :facet-conformance-fixture
  :provider-declaration-records
  :grant-records
  :capability-value-records
  :capability-scope-audit-logs
  :compile-time-provider-replay-records
  :runtime-provider-manifests
  :provider-conformance-results
  :provider-replacement-records
  :capability-attenuation-records
  :capability-revocation-records
  :capability-provider-conformance-fixture
  :alternative-macro-provider-declarations
  :alternative-macro-expansion-traces
  :alternative-macro-syntax-serializations
  :alternative-macro-hygiene-records
  :alternative-macro-explicit-capture-records
  :alternative-macro-build-effect-traces
  :alternative-macro-cache-decisions
  :alternative-macro-equivalence-reports
  :alternative-macro-facet-dispatch-records
  :alternative-macro-generated-validation-records
  :alternative-macro-conformance-fixture
  :alternative-type-provider-declarations
  :alternative-type-lowering-rules
  :alternative-type-fact-export-schemas])
