; Semantic decomposition of HEAD reader line 12567.
; Loaded into gravity.bootstrap; intentionally no ns form.

(def
 semantic-early-typed-pass-rejects-06
 ["SAFE12-ENGINE"
  "SAFE13-MODEL-EFFECT"
  "SAFE13-TOOL-CAPABILITY"
  "SAFE13-TOOL-SCHEMA"
  "SAFE13-PROMPT-INJECTION"
  "SAFE13-HUMAN-REVIEW"
  "SAFE13-SECRET"
  "SAFE13-GENERATED-CODE"
  "SAFE13-REPLAY"
  "SAFE13-RETENTION"
  "SAFE13-DESTRUCTIVE-TOOL"
  "SAFE15-PROOF-MISSING"
  "SAFE15-CERT-SCHEMA"
  "SAFE15-CERT-TRUST"
  "SAFE15-CERT-MISMATCH"
  "SAFE15-INVALIDATED"
  "SAFE15-CHECK-ERASE"
  "SAFE15-PROVIDER"
  "SAFE15-MANUAL"
  "SAFE15-BACKEND"
  "SAFE16-FIXTURE"
  "SAFE16-OUTCOME"
  "SAFE16-DIAGNOSTIC"
  "SAFE16-ARTIFACT"
  "SAFE16-PROFILE"
  "SAFE16-CERTIFICATE"
  "SAFE16-BACKEND"
  "SAFE16-REPORT"])
