; Semantic decomposition of HEAD reader line 12567.
; Loaded into gravity.bootstrap; intentionally no ns form.

(def
 semantic-early-typed-pass-emits-04
 [:safe-memory-runtime-borrow-check-records
  :safe-memory-region-lifetime-maps
  :safe-memory-arena-generation-graphs
  :safe-memory-reset-invalidation-records
  :safe-memory-provider-records
  :safe-memory-cleanup-records
  :safe-memory-linear-flow-graphs
  :safe-memory-terminal-operation-records
  :safe-memory-exceptional-cleanup-records
  :safe-memory-structured-resource-lowerings
  :safe-memory-generated-linear-flow-records
  :safe-memory-conformance-fixture
  :safe6-unsafe-island-records
  :safe6-safe-wrapper-records
  :safe6-operation-inventories
  :safe6-review-status-records
  :safe6-invariant-proof-links
  :safe6-generated-unsafe-provenance
  :safe6-policy-decision-records
  :safe6-dependency-unsafe-summaries
  :safe6-release-audit-reports
  :safe6-conformance-fixture
  :safe7-foreign-declaration-records
  :safe7-abi-protocol-records
  :safe7-type-mapping-records
  :safe7-ownership-lifetime-maps
  :safe7-safe-wrapper-audits
  :safe7-error-translation-maps
  :safe7-callback-safety-records
  :safe7-host-bridge-records
  :safe7-generated-binding-provenance
  :safe7-conformance-fixture
  :safe8-concurrency-graphs
  :safe8-task-capture-records
  :safe8-ownership-transfer-records
  :safe8-shared-state-access-records
  :safe8-synchronization-proof-records
  :safe8-atomic-memory-order-records
  :safe8-blocking-cancellation-records
  :safe8-backend-preservation-records
  :safe8-race-analysis-reports
  :safe8-conformance-fixture
  :safe9-numeric-mode-records
  :safe9-runtime-check-records
  :safe9-range-proof-records
  :safe9-floating-mode-records
  :safe9-elementary-approximation-records
  :safe9-relaxed-approval-records
  :safe9-optimization-proof-records
  :safe9-backend-lowering-records
  :safe9-conformance-fixture
  :safe11-taint-source-records
  :safe11-taint-flow-records
  :safe11-validator-contracts
  :safe11-residual-constraint-records])
