; Semantic decomposition of HEAD reader line 26010.
; Loaded into gravity.bootstrap; intentionally no ns form.

(defn
 semantic-early-artifact-emission-contract-and-backend-inputs
 [source-path state]
 (let
  [{:keys
    [source-overrides
     module
     interface-artifact
     native-artifact
     hosted-artifact
     specialized-artifact]}
   state]
  (assoc
   {}
   :kind
   :gravity/stage0-artifact-emission-artifact
   :task
   "P07-T05"
   :document-set
   ["B13" "B14"]
   :governing-documents
   artifact-emission-governing-documents
   :pass
   {:name :artifact-emission,
    :input :backend-interface-native-hosted-specialized-artifacts,
    :output :backend-artifact-provenance-graph,
    :requires
    [:backend-interface-artifact
     :native-lowering-artifact
     :hosted-lowering-artifact
     :specialized-lowering-artifact
     :common-manifest-schema
     :content-hashes
     :source-debug-map
     :compiler-provenance
     :dependency-provenance
     :safety-proof-evidence
     :effect-capability-summary
     :runtime-provider
     :target-abi-layout
     :reproducibility
     :conformance-evidence],
    :preserves
    [:source-spans
     :generated-origin-chain
     :types
     :effects
     :capabilities
     :safety
     :proofs
     :unsafe-audit-ids
     :profile
     :target
     :runtime
     :dependencies
     :diagnostics],
    :emits
    [:artifact-manifests
     :artifact-graph
     :content-hash-records
     :source-debug-map-record
     :compiler-provenance-record
     :dependency-provenance-record
     :safety-proof-certificate-bundle
     :effect-capability-summary
     :runtime-provider-summary
     :target-runtime-abi-layout-summary
     :reproducibility-record
     :conformance-evidence-reference
     :release-gate-record
     :artifact-emission-diagnostic-stream],
    :rejects artifact-emission-diagnostic-ids}
   :source-overrides
   source-overrides
   :module
   (select-keys
    module
    [:module
     :source-path
     :profile
     :target
     :effects
     :capabilities
     :safety
     :metadata])
   :backend-interface-artifact
   (select-keys
    interface-artifact
    [:kind
     :task
     :artifact-id
     :capability-based-proof
     :backend-interface-results])
   :native-lowering-artifact
   (select-keys
    native-artifact
    [:kind
     :task
     :artifact-id
     :capability-based-proof
     :native-lowering-results])
   :hosted-lowering-artifact
   (select-keys
    hosted-artifact
    [:kind
     :task
     :artifact-id
     :capability-based-proof
     :hosted-lowering-results])
   :specialized-lowering-artifact
   (select-keys
    specialized-artifact
    [:kind
     :task
     :artifact-id
     :capability-based-proof
     :specialized-lowering-results]))))
