; Semantic decomposition of HEAD reader line 3650.
; Loaded into gravity.bootstrap; intentionally no ns form.

(def
 semantic-early-checker-safety-late-keys
 [:safe10-attenuation-records
  :safe10-capability-requirement-records
  :safe10-conformance-records
  :safe10-grant-intersection-records
  :safe10-provider-selection-records
  :safe10-revocation-records
  :safe10-runtime-check-records
  :safe10-scope-check-records
  :safe10-secret-redaction-records
  :safe10-usage-summaries
  :safe11-conformance-records
  :safe11-deserialization-records
  :safe11-generated-taint-propagation
  :safe11-parameterization-records
  :safe11-prompt-tool-policy-records
  :safe11-residual-constraint-records
  :safe11-secret-redaction-records
  :safe11-sink-authorization-records
  :safe11-taint-flow-records
  :safe11-taint-source-records
  :safe11-unsafe-clear-audits
  :safe11-validator-contracts
  :safe12-alternative-engine-equivalence
  :safe12-conformance-records
  :safe12-facet-output-records
  :safe12-generated-origin-chains
  :safe12-generated-unsafe-island-records
  :safe12-hygiene-capture-records
  :safe12-macro-build-effect-records
  :safe12-macro-safety-declarations
  :safe12-taint-capability-propagation
  :safe13-conformance-records
  :safe13-generated-code-safety-records
  :safe13-human-review-records
  :safe13-memory-retention-policies
  :safe13-model-call-traces
  :safe13-model-output-taint-records
  :safe13-prompt-provenance-records
  :safe13-replay-records
  :safe13-tool-call-traces
  :safe13-tool-schema-validation-records
  :safe14-authority-diff-records
  :safe14-build-effect-summaries
  :safe14-conformance-records
  :safe14-generated-artifact-provenance
  :safe14-lockfile-records
  :safe14-native-dependency-records
  :safe14-package-safety-manifests
  :safe14-runtime-capability-summaries
  :safe14-signature-attestation-records
  :safe14-unsafe-summaries
  :safe15-backend-preservation-records
  :safe15-certificates
  :safe15-check-erasure-records
  :safe15-conformance-records
  :safe15-imported-certificate-verifications
  :safe15-invalidation-records
  :safe15-proof-provider-records
  :safe15-proof-records
  :safe15-trust-records
  :safe15-unsafe-wrapper-audit-views
  :safe16-backend-preservation-reports
  :safe16-certificate-inspections
  :safe16-conformance-records
  :safe16-conformance-reports
  :safe16-diagnostic-match-records
  :safe16-expected-outcome-manifests
  :safe16-fixture-manifests
  :safe16-profile-matrix-reports
  :safe16-runtime-check-inspections
  :safe16-unsafe-audit-inspections
  :safe9-backend-lowering-records
  :safe9-conformance-records
  :safe9-elementary-approximation-records
  :safe9-floating-mode-records
  :safe9-numeric-mode-records
  :safe9-optimization-proof-records
  :safe9-range-proof-records
  :safe9-relaxed-approval-records
  :safe9-runtime-check-records])
