; Semantic decomposition of HEAD reader line 3650.
; Loaded into gravity.bootstrap; intentionally no ns form.

(def
 semantic-early-checker-core-keys
 [:actor-channel-schemas
  :ai-tool-error-records
  :allocation-effect-records
  :allocator-runtime-manifests
  :atomic-ordering-records
  :branch-effect-summary
  :branch-type-narrowing-table
  :build-effect-log
  :cache-key-records
  :capability-attenuation-records
  :capability-records
  :capability-revocation-records
  :capability-scope-audit-logs
  :capability-value-records
  :compile-time-capability-proof-records
  :compile-time-evaluation-trace
  :compile-time-provider-replay-records
  :concurrency-effect-records
  :concurrency-facts
  :concurrency-ownership-transfer-records
  :constant-value-table
  :continuation-and-replay-safety-report
  :dispatch-mode-records
  :dynamic-boundary-records
  :effect-facts
  :error-type-declarations
  :exhaustiveness-report
  :facet-activation-records
  :facet-compatibility-records
  :facet-composition-records
  :facet-domain-ir-records
  :facet-generated-gravity-records
  :facet-manifests
  :facet-privacy-boundary-records
  :ffi-error-mapping-artifacts
  :function-signature-table
  :generated-form-provenance-records
  :generic-instantiation-records
  :grant-records
  :handled-effect-table
  :handler-capability-and-profile-report
  :hermetic-replay-records
  :host-error-normalization-records
  :host-interop-dispatch-records
  :initialization-facts
  :lifetime-region-facts
  :linear-resource-table
  :match-decision-trees
  :memory-facts
  :mmio-capability-records
  :ownership-borrow-facts
  :panic-lowering-records
  :pattern-ownership-facts
  :pattern-schema-validation-links
  :provider-conformance-results
  :provider-declaration-records
  :provider-replacement-records
  :provider-selection-records
  :race-analysis-reports
  :replay-effect-log
  :runtime-check-records
  :runtime-provider-manifests
  :safety-check-failure-records
  :scheduler-runtime-manifests
  :schema-type-links
  :standard-library-api-contracts
  :standard-library-compatibility-records
  :standard-library-documentation-examples
  :standard-library-namespace-contracts
  :standard-library-numeric-mode-records
  :standard-library-profile-availability-reports
  :standard-library-resource-records
  :standard-library-unsafe-wrapper-audits
  :synchronization-facts
  :task-scope-graphs
  :thrown-error-effect-records
  :type-category-coverage
  :type-facts
  :unreachable-branch-diagnostics
  :unsafe-raw-memory-audit-records
  :workflow-failure-records
  :workflow-replay-records])
