(ns gravity.bootstrap
  "Stage 0 Clojure bootstrap for the initial Gravity hosted subset.

  This seed exists to make the first Gravity milestone executable with a Lisp
  implementation. It is intentionally small and records unsupported behavior
  as diagnostics instead of pretending to be the final compiler."
  (:require [clojure.edn :as edn]
            [clojure.instant :as instant]
            [clojure.java.io :as io]
            [clojure.set :as set]
            [clojure.string :as str]
            [clojure.walk :as walk]
            [gravity.c2-artifact-identity :as c2-artifact-identity]
            [gravity.c2-reader-product-projection :as c2-reader-product-projection]
            [gravity.c2-reader-diagnostics :as c2-reader-diagnostics]
            [gravity.c2-source-identity :as c2-source-identity]
            [gravity.c2-pass-cache :as c2-pass-cache]
            [gravity.c2-lexical-validation :as c2-lexical-validation]
            [gravity.c3-artifact-identity :as c3-artifact-identity]
            [gravity.c3-reader-integrity :as c3-reader-integrity]
            [gravity.c3-syntax-diagnostics :as c3-syntax-diagnostics]
            [gravity.c3-literal-projection :as c3-literal-projection]
            [gravity.c3-syntax-construction :as c3-syntax-construction]
            [gravity.c3-syntax-evidence :as c3-syntax-evidence]
            [gravity.c3-syntax-verification :as c3-syntax-verification]
            [gravity.c4-macro-evidence :as c4-macro-evidence]
            [gravity.profile-validation :as profile-validation]
            [gravity.capability-validation :as capability-validation]
            [gravity.cli :as cli]
            [gravity.cli.diagnostic-presentation :as cli-diagnostic-presentation]
            [gravity.cli.entrypoint :as cli-entrypoint]
            [gravity.module-analysis :as module-analysis]
            [gravity.core-ast-lowering :as core-ast-lowering]
            [gravity.c5-name-resolution :as c5]
            [gravity.c6-core-lowering :as c6]
            [gravity.c7-type-checker :as c7]
            [gravity.c8-effect-checker :as c8]
            [gravity.c9-ownership-checker :as c9]
            [gravity.c10-safety-analysis :as c10]
            [gravity.c11-mir :as c11]
            [gravity.c12-domain-ir :as c12]
            [gravity.c13-optimization :as c13]
            [gravity.c14-lowering :as c14]
            [gravity.c15-diagnostics :as c15]
            [gravity.c16-incremental :as c16]
            [gravity.c17-plugin :as c17]
            [gravity.c18-verification :as c18]
            [gravity.compiler-pass-manifest :as compiler-pass-manifest]
            [gravity.compiler-verification-shared :as compiler-verification-shared]
            [gravity.optimization-lowering :as optimization-lowering]
            [gravity.p18.t00.orchestration :as p18-t00-orchestration]
            [gravity.p18.t00.semantics :as p18-t00-semantics]
            [gravity.p18.t04.semantics :as p18-t04-semantics]
            [gravity.darwin-publication :as darwin-publication]
            [gravity.digest :as digest]
            [gravity.diagnostics :as diagnostics]
            [gravity.macro-expansion :as macro-expansion]
            [gravity.reader-cursor :as reader-cursor]
            [gravity.reader-diagnostic-policy :as reader-diagnostic-policy]
            [gravity.reader-host-oracle :as reader-host-oracle]
            [gravity.reader-namespace :as reader-namespace]
            [gravity.reader-primitives :as reader-primitives]
            [gravity.source-span :as source-span]
            [gravity.source-unit :as source-unit]
            [gravity.syntax-object-stream :as syntax-object-stream]
            [gravity.syntax-origin :as syntax-origin])
  (:import [clojure.lang LineNumberingPushbackReader]
           [java.io StringReader]))

(clojure.core/require 'gravity.bootstrap-impl.loader)
(gravity.bootstrap-impl.loader/load-components!
 "gravity/bootstrap_impl/load_order.edn")
