

(def math1-diagnostic-ids
  ["MATH1-FAMILY" "MATH1-CONVERSION" "MATH1-NARROW"
   "MATH1-PRECISION" "MATH1-ROUNDING" "MATH1-BRANCH"
   "MATH1-ALLOCATION" "MATH1-EQUALITY" "MATH1-PROFILE"])

(def math7-diagnostic-ids
  ["MATH7-MISSING" "MATH7-SCOPE" "MATH7-DOWNGRADE"
   "MATH7-TARGET-DEFAULT" "MATH7-PRECISION" "MATH7-PROVIDER"
   "MATH7-ROUNDING" "MATH7-EXCEPTIONAL" "MATH7-RESIDUAL"])

(def math8-diagnostic-ids
  ["MATH8-MANIFEST" "MATH8-FORMAT" "MATH8-ROUNDING"
   "MATH8-NAN" "MATH8-INF" "MATH8-ZERO" "MATH8-DENORMAL"
   "MATH8-FMA" "MATH8-REASSOC" "MATH8-STATUS" "MATH8-BACKEND"])

(def math1-7-8-diagnostic-ids
  (vec (concat math1-diagnostic-ids math7-diagnostic-ids
               math8-diagnostic-ids)))

(def math2-diagnostic-ids
  ["MATH2-DECLARATION" "MATH2-DOMAIN" "MATH2-BRANCH"
   "MATH2-PROVIDER" "MATH2-NUMERIC-MODE" "MATH2-CERTIFICATE"
   "MATH2-EQUIVALENCE" "MATH2-EFFECT" "MATH2-TARGET"])

(def math3-diagnostic-ids
  ["MATH3-NODE" "MATH3-DOMAIN" "MATH3-CODOMAIN"
   "MATH3-BRANCH" "MATH3-PRECISION" "MATH3-SOURCE"
   "MATH3-REWRITE" "MATH3-EML" "MATH3-RUNTIME"])

(def math2-3-diagnostic-ids
  (vec (concat math2-diagnostic-ids math3-diagnostic-ids)))

(def math4-diagnostic-ids
  ["MATH4-EFIR" "MATH4-BASIS" "MATH4-DOMAIN" "MATH4-BRANCH"
   "MATH4-COMPLEX" "MATH4-TRACE" "MATH4-SEARCH"
   "MATH4-CANDIDATE" "MATH4-PROOF"])

(def math5-diagnostic-ids
  ["MATH5-CERT-SHAPE" "MATH5-EFIR" "MATH5-DOMAIN"
   "MATH5-BRANCH" "MATH5-APPROX-ERROR" "MATH5-ROUNDOFF"
   "MATH5-TARGET" "MATH5-CHECKER" "MATH5-SELECTION"])

(def math6-diagnostic-ids
  ["MATH6-CLAIM" "MATH6-DOMAIN" "MATH6-ROUNDING"
   "MATH6-BRANCH" "MATH6-PARTITION" "MATH6-BOUND"
   "MATH6-UNRESOLVED" "MATH6-PROVIDER" "MATH6-INVALIDATED"])

(def math9-diagnostic-ids
  ["MATH9-RULE-SHAPE" "MATH9-DOMAIN" "MATH9-BRANCH"
   "MATH9-SIDE-CONDITION" "MATH9-PROOF" "MATH9-TRACE"
   "MATH9-TERMINATION" "MATH9-COUNTEREXAMPLE" "MATH9-EGRAPH"
   "MATH9-EQUALITY"])

(def math6-9-diagnostic-ids
  (vec (concat math6-diagnostic-ids math9-diagnostic-ids)))

(def math10-diagnostic-ids
  ["MATH10-DETECT" "MATH10-EFIR" "MATH10-CANDIDATE"
   "MATH10-PROOF" "MATH10-CERTIFICATE" "MATH10-ROUNDING-TARGET"
   "MATH10-ROUNDING-INTERVAL" "MATH10-SYNTHESIS"
   "MATH10-FUSION" "MATH10-PROVIDER" "MATH10-PROVIDER-COMPARE"
   "MATH10-SIMD" "MATH10-GPU" "MATH10-AUTOTUNE"
   "MATH10-FALLBACK"])

(def math11-diagnostic-ids
  ["MATH11-FIXTURE" "MATH11-ORACLE" "MATH11-ARTIFACT"
   "MATH11-EFIR" "MATH11-EML" "MATH11-CERTIFICATE"
   "MATH11-INTERVAL" "MATH11-FLOATING" "MATH11-REWRITE"
   "MATH11-OPTIMIZATION" "MATH11-DIAGNOSTIC"])

(def math10-11-diagnostic-ids
  (vec (concat math10-diagnostic-ids math11-diagnostic-ids)))