

(defn safe-memory-conformance-fixture
  [checker-state]
  (let [covered (cond-> #{}
                  (seq (:safe-memory-operation-records checker-state))
                  (conj :safe2-memory-operation)
                  (seq (:safe-memory-runtime-check-records checker-state))
                  (conj :safe2-runtime-check)
                  (seq (:safe-memory-allocation-release-maps checker-state))
                  (conj :safe2-allocation-release)
                  (seq (:safe-memory-escape-analysis-records checker-state))
                  (conj :safe2-escape-analysis)
                  (seq (:safe-memory-proof-records checker-state))
                  (conj :safe2-optimization-proof)
                  (seq (:safe-memory-backend-preservation-records checker-state))
                  (conj :safe2-backend-preservation)
                  (seq (:safe-memory-unsafe-audit-records checker-state))
                  (conj :safe2-unsafe-audit)
                  (seq (:safe-memory-ownership-graphs checker-state))
                  (conj :safe3-ownership-graph)
                  (seq (:safe-memory-borrow-graphs checker-state))
                  (conj :safe3-borrow-graph)
                  (seq (:safe-memory-lifetime-interval-maps checker-state))
                  (conj :safe3-lifetime-map)
                  (seq (:safe-memory-transfer-records checker-state))
                  (conj :safe3-transfer)
                  (seq (:safe-memory-runtime-borrow-check-records checker-state))
                  (conj :safe3-runtime-borrow-check)
                  (seq (:safe-memory-region-lifetime-maps checker-state))
                  (conj :safe4-region-lifetime)
                  (seq (:safe-memory-arena-generation-graphs checker-state))
                  (conj :safe4-arena-generation)
                  (seq (:safe-memory-reset-invalidation-records checker-state))
                  (conj :safe4-reset-invalidation)
                  (seq (:safe-memory-provider-records checker-state))
                  (conj :safe4-provider)
                  (seq (:safe-memory-cleanup-records checker-state))
                  (conj :safe4-cleanup)
                  (seq (:safe-memory-linear-flow-graphs checker-state))
                  (conj :safe5-linear-flow)
                  (seq (:safe-memory-terminal-operation-records checker-state))
                  (conj :safe5-terminal-operation)
                  (seq (:safe-memory-exceptional-cleanup-records checker-state))
                  (conj :safe5-exceptional-cleanup)
                  (seq (:safe-memory-structured-resource-lowerings checker-state))
                  (conj :safe5-structured-lowering)
                  (seq (:safe-memory-generated-linear-flow-records checker-state))
                  (conj :safe5-generated-flow))
        missing (vec (remove covered safe-memory-required-families))]
    {:required-families safe-memory-required-families
     :covered-families (vec (sort-by name covered))
     :documents [:SAFE2 :SAFE3 :SAFE4 :SAFE5]
     :missing-families missing
     :status (if (empty? missing) :complete :incomplete)}))