

(defn capability-provider-conformance-fixture
  [checker-state]
  (let [declarations (:provider-declaration-records checker-state)
        grants (:grant-records checker-state)
        selections (:provider-selection-records checker-state)
        scope-audits (:capability-scope-audit-logs checker-state)
        replay-records (:compile-time-provider-replay-records checker-state)
        runtime-manifests (:runtime-provider-manifests checker-state)
        conformance-results (:provider-conformance-results checker-state)
        replacements (:provider-replacement-records checker-state)
        replacement-capabilities (set (map :capability replacements))
        selection-sources (set (map :selection selections))
        scope-categories (set (map :category scope-audits))
        covered (cond-> #{}
                  (seq declarations) (conj :declaration)
                  (seq grants) (conj :grant)
                  (seq (:capability-value-records checker-state))
                  (conj :explicit-capability-value)
                  (set/subset? l15-required-selection-sources selection-sources)
                  (conj :selection-source)
                  (set/subset? l15-required-scope-categories scope-categories)
                  (conj :scope-audit)
                  (and (some #(= :build (:phase %)) replay-records)
                       (some #(= :runtime (:phase %)) grants))
                  (conj :build-runtime-separation)
                  (seq replay-records) (conj :compile-time-replay)
                  (seq runtime-manifests) (conj :runtime-manifest)
                  (seq conformance-results) (conj :conformance)
                  (and (contains? replacement-capabilities :math/sin)
                       (or (contains? replacement-capabilities :memory/allocator)
                           (contains? replacement-capabilities :io/stdout)))
                  (conj :replacement)
                  (seq (:capability-attenuation-records checker-state))
                  (conj :attenuation)
                  (seq (:capability-revocation-records checker-state))
                  (conj :revocation)
                  (some #(and (:provider %)
                              (:version %)
                              (:scope %)
                              (:trust-level %)
                              (:conformance-suite %))
                        selections)
                  (conj :artifact-record))
        missing (vec (remove covered l15-required-provider-families))]
    {:required-families l15-required-provider-families
     :covered-families (vec (sort-by name covered))
     :missing-families missing
     :selection-sources-covered (vec (sort-by name selection-sources))
     :scope-categories-covered (vec (sort-by name scope-categories))
     :status (if (empty? missing) :complete :incomplete)}))