

(def safe-memory-diagnostic-ids
  ["SAFE2-UNINIT" "SAFE2-BOUNDS" "SAFE2-LIFETIME" "SAFE2-ESCAPE"
   "SAFE2-ALIAS" "SAFE2-ALLOC-FAILURE" "SAFE2-ALLOCATOR"
   "SAFE2-USE-AFTER-RELEASE" "SAFE2-DOUBLE-RELEASE" "SAFE2-RAW"
   "SAFE2-CHECK-ERASE" "SAFE2-PROFILE"
   "SAFE3-USE-AFTER-MOVE" "SAFE3-USE-AFTER-CONSUME"
   "SAFE3-BORROW-ESCAPE" "SAFE3-MUT-ALIAS"
   "SAFE3-MOVE-WHILE-BORROWED" "SAFE3-CONSUME-WHILE-BORROWED"
   "SAFE3-LIFETIME" "SAFE3-TASK-CAPTURE" "SAFE3-FFI-OWNERSHIP"
   "SAFE3-RUNTIME-CHECK" "SAFE3-UNSAFE-ALIAS"
   "SAFE4-REGION-ESCAPE" "SAFE4-ARENA-ESCAPE" "SAFE4-POST-RESET"
   "SAFE4-INNER-TO-OUTER" "SAFE4-RETURN" "SAFE4-TASK"
   "SAFE4-FFI-RETAIN" "SAFE4-CLEANUP" "SAFE4-PROVIDER"
   "SAFE4-RUNTIME-CHECK"
   "SAFE5-LEAK" "SAFE5-DOUBLE-CLOSE" "SAFE5-USE-AFTER-CLOSE"
   "SAFE5-BRANCH" "SAFE5-TRANSFER" "SAFE5-CAPTURE"
   "SAFE5-WRONG-PROVIDER" "SAFE5-CLEANUP-FAILURE" "SAFE5-CANCEL"
   "SAFE5-GENERATED"])