

(def perf1-diagnostic-ids
  ["PERF1-CLAIM" "PERF1-EVIDENCE" "PERF1-SAFETY" "PERF1-PROFILE"
   "PERF1-EFFECT" "PERF1-CAPABILITY" "PERF1-NUMERIC" "PERF1-TARGET"
   "PERF1-VARIANT"])

(def perf2-diagnostic-ids
  ["PERF2-CLAIM" "PERF2-RESIDUAL" "PERF2-ALLOCATION" "PERF2-BOXING"
   "PERF2-DISPATCH" "PERF2-REFLECTION" "PERF2-CHECK" "PERF2-PROFILE"
   "PERF2-EVIDENCE"])

(def perf3-diagnostic-ids
  ["PERF3-KEY" "PERF3-GUARD" "PERF3-EFFECT" "PERF3-HERMETIC"
   "PERF3-SOURCE-MAP" "PERF3-CACHE" "PERF3-PROFILE" "PERF3-PROOF"
   "PERF3-VARIANT"])

(def perf4-diagnostic-ids
  ["PERF4-LAYOUT" "PERF4-ABI" "PERF4-ADDRESS" "PERF4-ALIAS"
   "PERF4-ALIGN" "PERF4-PACKED" "PERF4-CACHE" "PERF4-DEVICE"
   "PERF4-PROOF"])

(def perf5-diagnostic-ids
  ["PERF5-MANIFEST" "PERF5-FINGERPRINT" "PERF5-SAFETY-GATE"
   "PERF5-CORRECTNESS-GATE" "PERF5-REGRESSION" "PERF5-NOISE"
   "PERF5-BASELINE" "PERF5-DRIFT"])

(def perf6-diagnostic-ids
  ["PERF6-DATA-MISSING" "PERF6-STALE" "PERF6-IDENTITY"
   "PERF6-PRIVACY" "PERF6-DECISION" "PERF6-SAFETY"
   "PERF6-REPRO" "PERF6-WORKLOAD"])

(def perf7-diagnostic-ids
  ["PERF7-CANDIDATE-SPACE" "PERF7-CANDIDATE-REJECTED"
   "PERF7-GUARD" "PERF7-SELECTION" "PERF7-CERTIFICATE"
   "PERF7-DISPATCH" "PERF7-REPRO" "PERF7-FALLBACK"])

(def perf5-7-diagnostic-ids
  (vec (concat perf5-diagnostic-ids perf6-diagnostic-ids
               perf7-diagnostic-ids)))

(def perf8-diagnostic-ids
  ["PERF8-LANE" "PERF8-ALIAS" "PERF8-BOUNDS" "PERF8-ALIGN"
   "PERF8-TAIL" "PERF8-NUMERIC" "PERF8-MATH" "PERF8-VOLATILE"
   "PERF8-INTRINSIC" "PERF8-CACHE"])

(def perf9-diagnostic-ids
  ["PERF9-BUDGET" "PERF9-LOOP" "PERF9-RECURSION" "PERF9-ALLOC"
   "PERF9-GC" "PERF9-BLOCKING" "PERF9-LOCK" "PERF9-PREEMPTION"
   "PERF9-EVIDENCE" "PERF9-OPTIMIZATION"])

(def perf10-diagnostic-ids
  ["PERF10-PROOF-MISSING" "PERF10-DOMINANCE" "PERF10-INVALIDATED"
   "PERF10-RESIDUAL" "PERF10-POLICY" "PERF10-BACKEND"
   "PERF10-CERTIFICATE" "PERF10-SOURCEMAP"])

(def perf8-10-diagnostic-ids
  (vec (concat perf8-diagnostic-ids perf9-diagnostic-ids
               perf10-diagnostic-ids)))