

(declare c1-architecture-artifact-id
         reader-canonical-hash
         c2-source-unit-record
         c2-token-record
         c2-form-record
         c2-literal-records
         c2-trivia-records
         c2-incremental-hashes
         c2-path-neutral-span
         c2-form-graph-metrics
         c2-reader-product-integrity-record
         c2-reader-artifact-id
         c2-reader-products
         c2-syntax-seed-stream
         c2-deferred-semantic-literals
         c2-reader-remap-exception!
         c2-lexical-product-validation
         c3-syntax-diagnostic-ids
         c3-syntax-governing-document
         c3-syntax-rejected-designs
         c3-reader-artifact-view
         c3-path-neutral-reader-artifact-view
         c3-path-neutral-syntax-object
         c3-validate-c2-reader-artifact!
         c3-deferred-ratio-descriptor-from-raw
         c3-artifact-id
         c3-syntax-object
         c3-generated-syntax-object
         c3-syntax-schema
         c3-hygiene-context-map
         c3-origin-chain-graph
         c3-metadata-ledger
         c3-generated-syntax-report
         c3-fact-ledger
         c3-syntax-serialization-fixture
         c3-syntax-verification-report
         c3-syntax-capability-proof
         c3-syntax-validate!
         sh04-syntax-semantic-source-id
         sh04-syntax-current-sh03-product-binding
         reader-project-context-for-source
         reader-project-root-record
         gravity-source-extension
         gravity-source-kind)