(defn- __gravity_bootstrap_checked_core_runtime_execution_evidence [state]
  (let [{:syms
         [source-path
          source-text
          requested-target
          authority-record
          construction-mode
          static-execution-evidence
          static-rebuild-token-candidate
          source-byte-count
          source-content-hash
          early-module-products
          module-attempt
          _
          early-module
          authoritative-front-end
          authoritative-module
          authoritative-records
          namespace-record
          function-record
          namespace-subject
          function-subject
          executable-form-records
          executable-form-by-id
          source-surface-validation
          malformed-quote-record
          source-surface-subject
          early-metadata-bearing-form
          c7-source-violation
          unsupported-quote-literal-form
          unsupported-numeric-form
          invalid-str-arity-form
          preflight-stage2-rule
          preflight-driver-rule
          preflight-plan
          preflight-plan-validation
          packet-delay
          front-end
          fresh-front-end
          top-level-forms
          reader-products
          c2-artifact
          form-tree
          root-form-ids
          indexes
          token-stream
          token-ordinal-by-id
          plan
          preflight-effect-requirements
          entrypoint
          functions
          definition
          declared-exports
          entrypoint-binding
          entrypoint-visibility
          source-function-records
          all-source-functions
          root-record-wrapper
          root-form-id
          root-record
          metadata-bearing-form
          root-syntax
          expanded-root-syntax
          function-shape
          instructions
          body-form-ids
          validation
          observed-operation-set
          ctx
          function-path
          function-origin
          body-product
          body-node-by-path
          body-node-ids
          function-node
          product
          effectful-diagnostic-subject
          pre-authority-nodes
          derived-effect-requirements
          effectful-reference?
          pure-admission
          runtime-rule
          authority-policy
          expected-authority-record
          authority-evidence
          ownership-normalized-nodes
          nodes
          core-operation-set
          packet
          packet-observed-operation-set
          packet-context
          pre-execution-facts
          dependency-order
          declared-effects
          declared-capabilities
          c2-semantic-input
          c3-semantic-input]} state
        adapter-output (when (and
                               effectful-reference?
                               (=
                                 :authoritative-artifact-construction
                                 construction-mode))
                         (p15-s23-reference-runtime-adapter-invoke
                           runtime-rule
                           p15-s23-stage2-runtime-artifact-closed-plan-function
                           [plan]
                           (:adapter-authority authority-record)))
        reference-execution-evidence (when effectful-reference?
                                       (case
                                         construction-mode
                                         :authoritative-artifact-construction
                                         (p15-s23-checked-core-reference-execution-evidence
                                           authority-evidence
                                           adapter-output)
                                         :static-verification-rebuild
                                         static-execution-evidence
                                         (p15-s23-closed-core-fail!
                                           "C8-CAPABILITY"
                                           source-path
                                           product
                                           {:missing-fact
                                            :supported-checked-core-construction-mode})))
        _ (when (and
                  effectful-reference?
                  (not
                    (p15-s23-checked-core-reference-execution-evidence-valid?
                      reference-execution-evidence
                      authority-evidence)))
            (p15-s23-closed-core-fail!
              "C10-CHECK"
              source-path
              product
              {:missing-fact :authenticated-reference-execution-evidence}))
        facts (if effectful-reference?
                (p15-s23-checked-core-bind-execution-audit-to-facts
                  pre-execution-facts
                  nodes
                  reference-execution-evidence)
                pre-execution-facts)]
    (assoc
      state
      'adapter-output
      adapter-output
      'reference-execution-evidence
      reference-execution-evidence
      '_
      _
      'facts
      facts)))
